### ISSUE TITLE
Make article h2 clickable

### ISSUE THREAD

**Issue by philoushka** [madskristensen/FeedCollector#2]
When I visited the site, I expected the title h2 to be a link to the article. 

I see the "Read the article" link does the job. The h2 should also be a link because:
- h2 is a larger touch target; especially important on mobile
- it makes more SEO sense that the link be rich in keywords

I have PR ready if you agree with the above.

**Comment by madskristensen** [comment]
That's a good idea. Should we then get rid of the `Read the article` link altogether?

**Comment by philoushka** [comment]
Keeping it either:
- is an obvious action for users who may not see that the h2 is a link
- adds noise

Your choice! (I'll make it so.)

**Comment by madskristensen** [comment]
Let's keep it for now. I just made a few commits. You may want to pull before sending the PR

**Comment by madskristensen** [comment]
Fixed years ago :)
